
all:	dt-iasa20-ietf100-slides.dvi dt-iasa20-ietf100-slides.pdf

dt-iasa20-ietf100-slides.dvi:	dt-iasa20-ietf100-slides.tex
	latex dt-iasa20-ietf100-slides.tex

dt-iasa20-ietf100-slides.pdf:	dt-iasa20-ietf100-slides.dvi
	dvipdf dt-iasa20-ietf100-slides.dvi dt-iasa20-ietf100-slides.pdf


clean:
	rm dt-iasa20-ietf100-slides.pdf dt-iasa20-ietf100-slides.dvi
